# Generated by Django 4.1.6 on 2023-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100, verbose_name='Name Product')),
                ('short_description', models.TextField(verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('score', models.CharField(choices=[('bad', 1), ('not bad', 2), ('good', 3), ('great', 4), ('perfect', 5)], max_length=20)),
            ],
        ),
    ]
