# Generated by Django 4.1.6 on 2023-02-20 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_alter_product_options_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='ProductImage/', verbose_name='تصاویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='score',
            field=models.CharField(blank=True, choices=[('bad', 1), ('not bad', 2), ('good', 3), ('great', 4), ('perfect', 5)], max_length=20, null=True, verbose_name='نمره'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage', models.TextField(verbose_name='Massage')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Date Time Modified')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='product.comment', verbose_name='Reply comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='product.product', verbose_name='محصول')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
