# Generated by Django 4.1.6 on 2023-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='CategoryiImage/')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Time Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Date Time Modified')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='product.category', verbose_name='Category'),
        ),
    ]
