# Generated by Django 4.1.6 on 2023-02-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
