# Generated by Django 4.1.6 on 2023-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_comment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.CharField(blank=True, choices=[('1', 'Bad'), ('2', 'Not Bad'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Perfect')], max_length=15, null=True, verbose_name='نمره'),
        ),
    ]
